### ISSUE TITLE
Error message after defining animal box

### ISSUE THREAD

**Issue by bdew42** [aharmer/pathtrackr#9]
I'm able to produce the directory full of jpegs with splitVideo() and then define the arena and the box for the animal using trackPath(), but immediately after I select the bottom right corner of the animal I get the following error message:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘extent’ for signature ‘"NULL"’

I've updated R and all of my packages, but to no avail.

The picture below is what the plot looks like.

Any thoughts?

![image](https://user-images.githubusercontent.com/37155020/37134871-73bfe75c-2268-11e8-9ce5-ea3e89678344.png)

**Comment by aharmer** [comment]
Hi, are you able to send me a sample video or download link so I can trouble shoot the problem?

Cheers.

____________________________________________

Dr Aaron Harmer - Research Officer
Institute of Natural and Mathematical Sciences
Massey University
Auckland, New Zealand
Phone: +64 9 213 6594
Email: a.harmer@massey.ac.nz
Photography: taranuiphotography.com


On 8 Mar 2018, 6:36 PM +1300, bdew42 <notifications@github.com>, wrote:

I'm able to produce the directory full of jpegs with splitVideo() and then define the arena and the box for the animal using trackPath(), but immediately after I select the bottom right corner of the animal I get the following error message:

Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘extent’ for signature ‘"NULL"’

I've updated R and all of my packages, but to no avail.

The picture below is what the plot looks like.

Any thoughts?

[image]<https://user-images.githubusercontent.com/37155020/37134871-73bfe75c-2268-11e8-9ce5-ea3e89678344.png>

**Comment by bdew42** [comment]
Certainly! Here is the link to the source file:

https://www.dropbox.com/s/clgzvfvqb46hh43/video.wmv?dl=0

Thanks.

**Comment by aharmer** [comment]
Apologies, there was a bug in the code after the last update, this error should now be fixed. You will need to reinstall `pathtrackr` with the bug fixes.

However, after a quick look through your video, you will probably not get very reliable tracking due to the inconsistency in your background. The moving containers and surface reflections generate a lot of distractions for the tracking function. I am working on adding an extra parameter to the `trackPath` function that should help with this to a degree, but surface reflections on water are a particularly troublesome issue to deal with in any tracking software.

**Comment by bdew42** [comment]
I uninstalled the package and did a reinstall with the install_github() command and I'm still getting the same error when I try and do the track. Any idea of what I did wrong?

**Comment by aharmer** [comment]
It seems there may have been a syncing error from my end to github so the package did not update as expected. Can you please try again, the updated version is definitely on github now. 

With regards to the noisy videos, you might want to clip out the first bunch of frames where the containers are swinging to help with tracking. You will also find a manual tracking function in `pathtrackr` called `manualPath`. This is obviously much slower as it requires you to click on the animal in each frame, but for very noisy videos it may be the only option.

**Comment by bdew42** [comment]
Great! I was able to do the track and have also been able to get it to work on a different video that is a little cleaner than the one I sent you. Result outputs look beautiful for the second video.

Unfortunately I'm having another error message pop up, this time when I use the makeVideo() function. Everything seems fine until it starts to track the animal, at some point I get the following error message:

Error in refelct(abs(frame.break - bg.med)) : could not find function "refelct"

The highest I get is about 14% done before it gave the error.

Any thoughts?

Also, thanks for letting me know about the manualPath function, it's a bit tedious but could be very helpful.

**Comment by aharmer** [comment]
Should be fixed now.

**Comment by bdew42** [comment]
Well that's just cool! Thanks for building this package, it is absolutely amazing and it is going to add a new dimension to my research.

**Comment by aharmer** [comment]
Hi, thanks for the comments and finding those bugs. Just out of curiosity, what institute are you at?


____________________________________________

Dr Aaron Harmer - Research Officer
Institute of Natural and Mathematical Sciences
Massey University
Auckland, New Zealand
Phone: +64 9 213 6594
Email: a.harmer@massey.ac.nz
Photography: taranuiphotography.com


On 14 Mar 2018, 7:31 AM +1300, Bill <notifications@github.com>, wrote:

Well that's just cool! Thanks for building this package, it is absolutely amazing and it is going to add a new dimension to my research.

**Comment by bdew42** [comment]
I'm at Trent University in Peterborough, Ontario, Canada. My contact details as well as some of my work is found here:
https://www.trentu.ca/biology/faculty-research/faculty/william-dew

If there is anyway I can help with this package let me know, keeping in mind I have no idea how to program or produce packages in R... :)
